version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vtt_postgres
    environment:
      POSTGRES_USER: vtt_admin
      POSTGRES_PASSWORD: vtt_password
      POSTGRES_DB: vtt_database
    ports:
      - "5432:5432"
    volumes:
      - vtt_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


volumes:
  vtt_data: